src/Entity/Cliente.php
<?php

namespace App\Entity;

use App\Repository\ClienteRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: ClienteRepository::class)]
#[UniqueEntity('Dni')]
class Cliente
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 9, unique: true)]
    private ?string $Dni = null;

    #[ORM\Column(length: 255)]
    private ?string $Nombre = null;

    #[ORM\Column(length: 255)]
    private ?string $Apellido = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Telefono = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $Direccion = null;

    #[ORM\OneToMany(mappedBy: 'cliente', targetEntity: Venta::class)]
    private ?Collection $Ventas;

    /**
     * Cliente constructor.
     * @param int|null $id
     * @param string|null $Dni
     * @param string|null $Nombre
     * @param string|null $Apellido
     * @param string|null $Telefono
     * @param string|null $Direccion
     * @param Collection $Ventas
     */
    public function __construct(?string $Dni = null, ?string $Nombre = null, ?string $Apellido = null, ?string $Telefono = null, ?string $Direccion = null, ?int $id = null, Collection $Ventas = null)
    {
        $this->id = $id;
        $this->Dni = $Dni;
        $this->Nombre = $Nombre;
        $this->Apellido = $Apellido;
        $this->Telefono = $Telefono;
        $this->Direccion = $Direccion;
        $this->Ventas = $Ventas;
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDni(): ?string
    {
        return $this->Dni;
    }

    public function setDni(string $Dni): self
    {
        $this->Dni = $Dni;

        return $this;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): self
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getApellido(): ?string
    {
        return $this->Apellido;
    }

    public function setApellido(string $Apellido): self
    {
        $this->Apellido = $Apellido;

        return $this;
    }

    public function getTelefono(): ?string
    {
        return $this->Telefono;
    }

    public function setTelefono(?string $Telefono): self
    {
        $this->Telefono = $Telefono;

        return $this;
    }

    public function getDireccion(): ?string
    {
        return $this->Direccion;
    }

    public function setDireccion(?string $Direccion): self
    {
        $this->Direccion = $Direccion;

        return $this;
    }

    /**
     * @return Collection<int, Venta>
     */
    public function getVentas(): Collection
    {
        return $this->Ventas;
    }

    public function addVenta(Venta $venta): self
    {
        if (!$this->Ventas->contains($venta)) {
            $this->Ventas->add($venta);
            $venta->setCliente($this);
        }

        return $this;
    }

    public function removeVenta(Venta $venta): self
    {
        if ($this->Ventas->removeElement($venta)) {
            // set the owning side to null (unless already changed)
            if ($venta->getCliente() === $this) {
                $venta->setCliente(null);
            }
        }

        return $this;
    }
    
    public function __toString() {
        return $this->Apellido . ', ' . $this->Nombre;
    }
}

src/Entity/Venta.php
<?php

namespace App\Entity;

use App\Repository\VentaRepository;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

#[ORM\Entity(repositoryClass: VentaRepository::class)]
//#[UniqueEntity('Factura')]
class Venta
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Factura = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?DateTimeInterface $Fecha = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 11, scale: 2)]
    private ?string $Total = null;

    #[ORM\Column(length: 15)]
    private ?string $Estado = null;

    #[ORM\OneToMany(mappedBy: 'venta', targetEntity: DetalleVenta::class, orphanRemoval: true, cascade: ['persist'])]
    private Collection $detalles;

    #[ORM\ManyToOne(inversedBy: 'Ventas')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Cliente $cliente = null;

    #[ORM\ManyToOne(inversedBy: 'Ventas')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Usuario $usuario = null;

    #[ORM\Column(length: 10)]
    private ?string $TipoFactura = null;

    public function __construct()
    {
        $this->detalles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFactura(): ?string
    {
        return $this->Factura;
    }

    public function setFactura(string $Factura): self
    {
        $this->Factura = $Factura;

        return $this;
    }

    public function getFecha(): ?DateTimeInterface
    {
        return $this->Fecha;
    }

    public function setFecha(DateTimeInterface $Fecha): self
    {
        $this->Fecha = $Fecha;

        return $this;
    }

    public function getTotal(): ?string
    {
        return $this->Total;
    }

    public function setTotal(string $Total): self
    {
        $this->Total = $Total;

        return $this;
    }

    public function getEstado(): ?string
    {
        return $this->Estado;
    }

    public function setEstado(string $Estado): self
    {
        $this->Estado = $Estado;

        return $this;
    }

    /**
     * @return Collection<int, DetalleVenta>
     */
    public function getDetalles(): Collection
    {
        return $this->detalles;
    }

    public function addDetalle(DetalleVenta $detalle): self
    {
        if (!$this->detalles->contains($detalle)) {
            $this->detalles->add($detalle);
            $detalle->setVenta($this);
        }

        return $this;
    }

    public function removeDetalle(DetalleVenta $detalle): self
    {
        if ($this->detalles->removeElement($detalle)) {
            // set the owning side to null (unless already changed)
            if ($detalle->getVenta() === $this) {
                $detalle->setVenta(null);
            }
        }

        return $this;
    }

    public function getCliente(): ?Cliente
    {
        return $this->cliente;
    }

    public function setCliente(?Cliente $cliente): self
    {
        $this->cliente = $cliente;

        return $this;
    }

    public function getUsuario(): ?Usuario
    {
        return $this->usuario;
    }

    public function setUsuario(?Usuario $usuario): self
    {
        $this->usuario = $usuario;

        return $this;
    }

    public function getTipoFactura(): ?string
    {
        return $this->TipoFactura;
    }

    public function setTipoFactura(string $TipoFactura): self
    {
        $this->TipoFactura = $TipoFactura;

        return $this;
    }
}

src/Form/VentaType.php
<?php

namespace App\Form;

use App\Entity\Cliente;
use App\Entity\Venta;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VentaType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add(
                'cliente',
                EntityType::class,
                ['class' => Cliente::class, 'attr' => ['class' => 'js-choice']]
            )
            ->add(
                'TipoFactura',
                \Symfony\Component\Form\Extension\Core\Type\ChoiceType::class,
                ['choices' => ['C' => 'C', 'B' => 'B', 'A' => 'A'], 'label' => 'Tipo de Factura']
            )
            ->add(
                'Factura',
                TextType::class,
                ['required' => true, 'label' => 'Nº de Factura']
            )
            ->add(
                'Fecha',
                DateTimeType::class,
                ['html5' => true, 'widget' => 'single_text',
                'attr' => ['placeholder' => 'aaaa-mm-ddThh:mm:ss',
                'onchange'=>'fechacel("venta_Fecha");']]
            )
            //->add('Total')
            //->add('Estado')
            //->add('usuario')
            ->add(
                'detalles',
                CollectionType::class,
                [
                    'entry_type' => DetalleVentaType::class,
                    'label' => false,
                    'entry_options' => ['label' => false],
                    'allow_add' => true,
                    'by_reference' => false,
                ]
            )
            ->add('Submit', SubmitType::class, ['label' => 'Guardar', 'attr' => ['style' => "float:right;"]]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Venta::class,
        ]);
    }
}

src/Controller/VentaController.php
<?php

namespace App\Controller;

use App\Entity\Producto;
use App\Entity\Usuario;
use App\Entity\Venta;
use App\Form\VentaType;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Attribute\CurrentUser;

#[IsGranted('ROLE_USER')]
class VentaController extends AbstractController
{

    private EntityManagerInterface $em;
    private EntityRepository $cr;

    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
        $this->cr = $this->em->getRepository(Venta::class);
    }

    #[Route('/venta', name: 'app_venta')]
    public function index(): Response
    {
        $ventas = $this->cr->findBy([], ['id' => 'DESC']);

        return $this->render('venta/index.html.twig', [
            'ventas' => $ventas
        ]);
    }

    #[Route('/venta/nuevo', name: 'app_venta_new')]
    public function new(Request $request): Response
    {
        $venta = new Venta();
        $venta->setFecha(new DateTime());

        $pr = $this->em->getRepository(Producto::class);
        $productos_stock = $pr->findAllStock();
        $productos_precio = $pr->findAllPrecio();


        $form = $this->createForm(VentaType::class, $venta);
        $form->handleRequest($request);


        if ($form->isSubmitted() && $form->isValid()) {

            $detalles = $venta->getDetalles();
            $detalles_productos_id = [];
            $total = 0;
            $error = '';

            foreach ($detalles as $k => $detalle) {

                if ($detalles[$k]->getCantidad() < 1) {
                    unset($detalles[$k]);
                } else {

                    $detalles[$k]->setCostoUnitario($detalle->getProducto()->getPrecio());
                    $detalle->getProducto()->setStock($detalle->getProducto()->getStock() - $detalle->getCantidad());
                    $total = $total + ($detalles[$k]->getCostoUnitario() * $detalles[$k]->getCantidad());

                    //Eliminar producto repetido y acumular su cantidad con el detalle ya guardado
                    if (array_key_exists($detalle->getProducto()->getId(), $detalles_productos_id)) {
                        $detalles_productos_id[$detalle->getProducto()->getId()]->setCantidad(
                            $detalles_productos_id[$detalle->getProducto()->getId()]->getCantidad() +
                                $detalle->getCantidad()
                        );

                        unset($detalles[$k]);
                    } else {
                        $detalles_productos_id[$detalle->getProducto()->getId()] = $detalle;
                    }

                    if ($detalle->getProducto()->getStock() < 0) {
                        $error = "No puedes vender tantos/as " . $detalle->getProducto()->getNombre() . ". Revisa tu pedido.";
                        break;
                    }
                }
            }
            if (count($detalles) < 1) {
                $error = "Debe seleccionar un producto para vender.";
            }

            if ($error === '') {

                $venta->setTotal($total);
                $venta->setEstado('Normal');
                $venta->setUsuario($this->getUser());

                $this->em->persist($venta);
                $this->em->flush();

                $this->addFlash('success', 'Se realizó la venta correctamente. Puede <a href="' . $this->generateUrl('app_venta_view', ['id' => $venta->getId(), 'print' => 'print']) . '" target="_blank">imprimir el remito aquí</a>.');

                return $this->redirectToRoute('app_venta');
            } else {
                $this->addFlash('error', $error);
            }
        }

        return $this->render('venta/new.html.twig', [
            'form' => $form->createView(),
            'productos_stock' => json_encode($productos_stock),
            'productos_precio' => json_encode($productos_precio)
        ]);
    }

    #[Route('/venta/remito/{id}/{print}', name: 'app_venta_view')]
    public function edit(int $id, string $print = 'no'): Response
    {
        $venta = $this->cr->find($id);

        return $this->render('venta/view.html.twig', [
            'venta' => $venta,
            'print' => $print

        ]);
    }

    #[Route('/venta/delete/{id}', name: 'app_venta_delete', methods: ['GET', 'HEAD'])]
    public function delete(int $id): Response
    {

        if ($id < 1)
            throw new AccessDeniedHttpException();

        $venta = $this->cr->find($id);

        return $this->render('venta/delete.html.twig', [
            'venta' => $venta
        ]);
    }

    #[Route('/venta/delete', name: 'app_venta_dodelete', methods: ['DELETE'])]
    public function doDelete(Request $request): Response
    {

        $submittedToken = $request->request->get('_token');
        if (!$this->isCsrfTokenValid('borrarcosa', $submittedToken)) {
            throw new AccessDeniedHttpException();
        }

        $id = $request->get('id');
        if (is_numeric($id)) {
            $id = intval($id);
            if ($id < 1) {
                throw new AccessDeniedHttpException();
            }
        } else {
            throw new AccessDeniedHttpException();
        }

        $venta = $this->cr->find($id);
        if ($venta->getEstado() == 'Anulado') {
            throw new AccessDeniedHttpException();
        }

        $detalles = $venta->getDetalles();

        foreach ($detalles as $k => $detalle) {
            $p = $detalle->getProducto();
            $p->setStock($p->getStock() + $detalle->getCantidad());
            $this->em->persist($p);
        }

        $venta->setEstado('Anulada');

        $this->em->flush();

        $this->addFlash('success', 'Se anuló la venta correctamente.');

        return $this->redirectToRoute('app_venta');
    }
}

templates/venta/delete.html.twig
{% extends 'base.html.twig' %}

{% block title %}SisVentas - Ventas{% endblock %}
{% block bodytitle %}Anular Venta{% endblock %}

{% block body %}
    <form action="{{ path('app_venta_dodelete') }}" method="POST">
        <div class="alert alert-danger">
            <p class="fw-bold">¿Está seguro de anular esta Venta?</p>
            <p>El stock sera devuelto a los productos correspondientes.</p>
        </div>

{{ include('venta/remito.html.twig', with_context = true) }}

        <input type="hidden" name="id" value="{{ venta.id }}" />
        <input type="hidden" name="_method" value="DELETE" />
<input type="hidden" name="_token" value="{{ csrf_token('borrarcosa') }}"/>
 
            
<input type="submit" value="Anular" class="btn btn-danger" style="float: right" /><a href="{{ path('app_venta') }}" class="btn btn-secondary">Volver</a>

    </form>
{% endblock %}

templates/venta/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}SisVentas - Ventas{% endblock %}
{% block bodytitle %}Ventas{% endblock %}

{% block body %}
    {% for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message|raw }}
        </div>
    {% endfor %}
    <a href="{{ path('app_venta_new') }}" class="btn btn-success"><i class="bi bi-plus-circle-fill"></i> Vender</a>
    <table class="table table-striped table-sm table-hover" id="tablaventa">
        <thead>
            <tr>
                {# <th>Id</th> #}
                <th>Remito Nº</th>
                <th>Fecha</th>
                <th>Total</th>
                <th>Estado</th>
                    {# <th>Teléfono</th>
                    <th>Dirección</th> #}
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for venta in ventas %}
                <tr{% if venta.Estado == 'Anulada' %} style="background-color: #faa"{% endif %}>
                    {# <td>{{ venta.id }}</td> #}
                    <td>{{ venta.id|u.truncate(13, '...') }}</td>
                    <td>{{ venta.Fecha|date("d/m/Y") }}</td>
                    <td>$ {{ venta.Total }}</td>
                    <td>
                    {% if venta.Estado == 'Normal' %}
                    <i class="bi bi-check2-circle"></i>Ok 
                    {% else %}
                    <i class="bi bi-x-circle"></i> Anulada
                    {% endif %}
                    </td>
                    {# <td>{{ venta.Telefono }}</td>
                    <td>{{ venta.Direccion }}</td> #}
                    <td>
                        <a href="{{ path('app_venta_view',{'id':venta.id}) }}" class="btn btn-primary btn-sm" title="Ver Remito" target="_blank"><i class="bi bi-card-text"></i></a>
                           
                        <a href="{% if venta.Estado == 'Anulada' %}#{% else %}{{ path('app_venta_delete',{'id':venta.id}) }}{% endif %}" class="btn btn-danger btn-sm {% if venta.Estado == 'Anulada' %} disabled{% endif %}" title="Anular"><i class="bi bi-x-circle"></i></a>
                        
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/venta/new.html.twig
{% extends 'base.html.twig' %}
{% form_theme form with [
'bootstrap_5_layout.html.twig',
_self
] %}

{% block _venta_Fecha_row %}
    <div class="mb-3">
        {{ form_label(form) }}

        <input type="datetime-local" id="{{ form.vars.id }}" {% for k,v in form.vars.attr %}{{ k }}="{{ v }}"{% endfor %}class="form-control{{ form.vars.required ? ' falserequired'
        }}" value="{{ form.vars.value }}">
        <input type="hidden" value="{{ form.vars.value }}" id="{{ form.vars.id }}_h" name="{{ form.vars.full_name }}">
        {{ form_errors(form) }}
    </div>
{% endblock %}

{% block title %}SisVentas - Ventas
{% endblock %}
{% block bodytitle %}Venta
{% endblock %}

{% block body %}
    <script>
        const ps = {{ productos_stock|raw }};
        const pp = {{ productos_precio|raw }};
    </script>

    {% for message in app.flashes('error') %}
        <div class="alert alert-danger">
            {{ message }}
        </div>
    {% endfor %}

    {% for message in app.flashes('success') %}
        <div class="alert alert-success">
            {{ message }}
        </div>
    {% endfor %}

    {{ form_start(form) }}
    {{ form_row(form.cliente) }}
    <div class="row">
        <div class="col-md-4">
            {{ form_row(form.TipoFactura) }}
        </div>
        <div class="col-md-8">
            {{ form_row(form.Factura) }}
        </div>
    </div>
    {{ form_row(form.Fecha) }}

    <h3 style="display: inline">Productos</h3>
    <button type="button" class="mx-2 mb-2 btn btn-success btn-sm add_item_link" data-collection-holder-class="detalles">
        <i class="bi bi-plus-circle"></i>
        Agregar</button>
    <table class="table table-striped table-sm">
        <thead>
            <tr>
                <th>Producto</th>
                <th>Cantidad</th>
                <th></th>
            </tr>
        </thead>
        <tbody class="detalles" data-index="{{ form.detalles|length > 0 ? form.detalles|last.vars.name + 1 : 0 }}" data-prototype="{{ '<td><input type="hidden" value="0" class="producto_stock" />'|e('html_attr') }}{{ form_row(form.detalles.vars.prototype.producto)|e('html_attr') }}{{'</td><td>'|e('html_attr') }}{{ form_row(form.detalles.vars.prototype.Cantidad)|e('html_attr') }}</td>">

            {% for detalle in form.detalles %}
                <tr class="animate__animated animate__flash">
                    <td style="width: 80%"><input type="hidden" value="0" class="producto_stock"/>{{ form_row(detalle.producto) }}</td>
                    <td style="width: 15%">{{ form_row(detalle.Cantidad) }}</td>
                </tr>
            {% endfor %}
        </tbody>
    <tfoot>
    <tr>
    
        <th scope="row">Total:{# <input type="" id="totalprod" value="0" /> #}</th>
        <th scope="row" id="totalhtml">$ 00,00</th>
        <th scope="row"></th>
    </tr>
    </tfoot>
    </table>
    {{ form_rest(form) }}
    {{ form_end(form) }}

    <a href="{{ path('app_venta') }}" class="btn btn-secondary">Volver</a>


{% endblock %}

templates/venta/remito.html.twig
<table class="table table-sm table-condensed">
        <tr>
            {# <th>Id</th> #}
            <th scope="row">Cliente</th>
            <td>{{ venta.cliente }}</td>
            <th scope="row">Fecha</th>
            <td>{{ venta.Fecha|date("d/m/Y") }}</td>
        </tr>
        <tr>
            <th scope="row">Factura</th>
            <td>[{{ venta.TipoFactura }}] {{ venta.Factura }}</td>
            <th scope="row">Remito Nº</th>
            <td>{{ venta.id }}</td>
        </tr>
</table>
<table class="table table-sm table-condensed">
    <thead>
        <tr>
            {# <th>Id</th> #}
            <th>Cod.</th>
            <th>Producto</th>
            <th>Precio Unitario</th>
            <th>Cantidad</th>
            <th>Sub-Total</th>
        </tr>
    </thead>
    <tbody>
        {% for detalle in venta.getDetalles %}
            <tr>
                <td>{{ detalle.id }}</td>
                <td>{{ detalle.Producto.nombre }}</td>
                <td>$ {{ detalle.CostoUnitario|number_format(2, '.', ',') }}</td>
                <td>{{ detalle.Cantidad }}</td>
                <td>$ {{ (detalle.CostoUnitario * detalle.Cantidad)|number_format(2, '.', ',') }}</td>
            </tr>
        {% endfor %}
    </tbody>
    <tfoot>
        <tr>
            {# <th>Id</th> #}
            <th colspan="3"></th>
            <th>Total</th>
            <th>$ {{ venta.Total|number_format(2, '.', ',') }}</th>
        </tr>
    </tfoot>
</table>
        

templates/venta/view.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta charset="UTF-8">
        <title>SisVentas - Remito</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>🛍️️</text></svg>">
        <link rel="stylesheet" href="{{ asset('css/styles.css') }}" />
    </head>
    <body{{ print == 'print' ? ' onload="window.print();"' : '' }}>
        <main class="container">
            <div class="bg-white pt-2 rounded-lg cuerpo">
                <div class="mx-auto text-center h-25">
                    <span class="display-1 fw-bold">{{ venta.Estado == 'Anulada' ? 'Anulado' : 'X' }}</span>
                </div>
                {{ include('venta/remito.html.twig', with_context = true) }}
                <button class="btn btn-primary d-print-none" style="float: right" onclick="window.print();">Imprimir</button><button class="btn btn-secondary d-print-none" onclick="window.close()">Cerrar</button>
            </div></main>
    </body>
</html>